server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8200/v1/oidc/issuer
  cloud:
    vault:
      uri: http://localhost:8200
      authentication: token
      token: my-root-token